# Pre-commit configuration for Swarm Panel frontend
repos:
  # Python code formatting
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3.10
        files: ^frontend/
        exclude: ^frontend/tests/

  # Python import sorting
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
        files: ^frontend/
        exclude: ^frontend/tests/

  # Python code analysis
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-docstrings]
        files: ^frontend/
        exclude: ^frontend/tests/
        args: [
          "--max-line-length=100",
          "--docstring-convention=google",
          "--ignore=D100,D104,W503"
        ]

  # Type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
      - id: mypy
        additional_dependencies: [types-all]
        files: ^frontend/
        exclude: ^frontend/tests/
        args: [
          "--ignore-missing-imports",
          "--disallow-untyped-defs",
          "--check-untyped-defs"
        ]

  # Security checks
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
        files: ^frontend/
        exclude: ^frontend/tests/

  # YAML formatting
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: detect-private-key
